### PR TITLE
Removed autoloader function

### PR DESCRIPTION
**Pull request by gaborkoszegi**
Modified composer autoload with PSR-4

### CODE REVIEW

**Comment by iCalcreator** [comment]
Great job, very nice, 
will include it in the coming iCalcreator 2.24 release.
Btw, lower case kigkonsult ;)

I need external testers about mid march, interested?

**Comment by gaborkoszegi** [comment]
Thanks :) Yes, I'm interested.

**Comment by iCalcreator** [comment]
Please mail directly, have some questions about the coming release.

**Comment by iCalcreator** [comment]
Ref 2.23.18

**Pull request closed without merging**
