### PR TITLE
Use PHP 7 constructors

### LINKED ISSUE #67: Make 2.20.x version that is compatible with PHP 7
Drupal module Date iCal (date_ical) is not compatible with versions of iCalcreator after 2.20. This version is not compatible with PHP 7. There is already a patch to iCalcreator that makes it compatible with PHP 7:
https://www.drupal.org/project/date_ical/issues/2707373#comment-11574961
I suggest applying this patch and releasing 2.20.3.

### PR DESCRIPTION
**Pull request by lkmorlan**
This fixes #67. This is based on 2.20.2 (e3dbec2).

### CODE REVIEW

**Comment by iCalcreator** [comment]
To solve the issue, upgrade to 2.24.2.
But I recommend to upgrade to 2.26, PSR1+4 fixed.
2.26.x will be released early december, next stable.

**Comment by joejoseph00** [comment]
2.20.2 is the backbone of the date_ical module  would be nice to have a 2.20.3 release for compatibility reasons.  https://www.drupal.org/project/date_ical/issues/2707373#comment-12857937

**Comment by lkmorlan** [comment]
Yes, iCalcreator 2.24 and date_ical are not compatible. We need this in iCalcreator 2.20.

**Comment by lkmorlan** [comment]
My fork of iCalcreator 2.20.x now supports PHP 7.4 in version 2.20.4.

https://github.com/lkmorlan/iCalcreator/releases/tag/v2.20.4

**Pull request closed without merging**
